### ISSUE TITLE
[PE-D][Tester E] findu filters based on the list displayed to user, instead of on the whole list

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T17-1/tp#201]
**Describe the bug**
If the user has previously used a `find` comment, using the `findu` comment filters on the list currently displayed, instead of filtering on the entire list.

**Steps to Reproduce**
With the sample data provided,

1. `find Alex`
2. `findu u/NTU`.

It will show no persons found.

**Expected behavior**
It is expected that `findu u/NTU` should filter from the overall list, instead of just the current list displayed. In the sample data given, there is at least one person with u/NTU, so it should at least show at least 1 person in the list.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: zaidansani/ped#1

**Comment by chenle228** [comment]
specify the logic
