### ISSUE TITLE
[PE-D][Tester C] findw command returns unexpected result

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T17-1/tp#215]
findw command doesn't work with the format findw w/COMPANY,ROLE fields specified as mentioned in DG 

![Screenshot 2024-11-08 at 4.42.45 PM.png](https://raw.githubusercontent.com/weibinlim/ped/main/files/f56b80cb-0944-419a-8351-4a5ef6375a63.png)

![Screenshot 2024-11-08 at 4.42.03 PM.png](https://raw.githubusercontent.com/weibinlim/ped/main/files/b08ad500-a363-4328-8472-538424c04f75.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: weibinlim/ped#3

**Comment by jeremychiaaaaa** [comment]
should be findw w/Role, Company
