### ISSUE TITLE
[PE-D][Tester A] Cannot delete interests from contacts

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T17-1/tp#227]
**Steps to reproduce:**
None

**Expected:**
A way to delete interests from a contact.

**Actual:**
There is no way to delete interests without deleting the whole contact, from what is written in the UG.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: LeeZeHao/ped#7

**Comment by verakohh** [comment]
update UG under edit command that this is possible for optional fields
