### ISSUE TITLE
[PE-D][Tester C] Editing interest of a person allows for space to be an interest

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T17-1/tp#233]
When editing a person's interest, "space" is a valid interest

![image.png](https://raw.githubusercontent.com/weibinlim/ped/main/files/769a76a3-b623-4cb6-aa8a-e1ad6d78c890.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: weibinlim/ped#5

**Comment by chenle228** [comment]
frame it as deleting interest
