### ISSUE TITLE
[PE-D][Tester C] Command addw does not work with certain company name format

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T17-1/tp#253]
addw does not work with company names of more than 1 letter

![image.png](https://raw.githubusercontent.com/weibinlim/ped/main/files/bf483e35-76b1-46ba-a36a-ea6a3be1bfb8.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: weibinlim/ped#10

**Comment by chenle228** [comment]
add in our limitation
