### ISSUE TITLE
[PE-D][Tester C] Typo in Developer Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T17-1/tp#258]
There is a typo in the developer guide manual testing portion.

![image.png](https://raw.githubusercontent.com/weibinlim/ped/main/files/033698df-a5fa-4066-8aad-67379ad322ca.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: weibinlim/ped#13

**Comment by jeremychiaaaaa** [comment]
should be finding contacts by university 

testcase 2 should be findu

**Comment by chenle228** [comment]
screenshot not clear enough - nvr specify typo
