### ISSUE TITLE
[PE-D][Tester D] Different error outputs for invalid index

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T17-1/tp#259]
Command input: edit 100000000000 p/12345678
Expected: Invalid index error
Actual: Invalid Command error

![image.png](https://raw.githubusercontent.com/wrjgold/ped/main/files/0199bc57-a6f8-4dc1-b840-abb45661c13a.png)

![image.png](https://raw.githubusercontent.com/wrjgold/ped/main/files/84e06f8e-d69a-498e-934f-c68b05b9f5fe.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: wrjgold/ped#16

**Comment by chenle228** [comment]
specify the valid range / max allowable of index
